#!/bin/zsh

export LANG="en_US.UTF-8"
export LC_ALL=""
export EDITOR=vim
export PGCLIENTENCODING="utf8"
export LD_LIBRARY_PATH=/usr/local/lib/gcc48

bindkey    "^[[3~"          delete-char
bindkey    "^[3;5~"         delete-char
bindkey    '^R'             history-incremental-search-backward

autoload -U promptinit
promptinit
prompt zefram

#------------------------------
## Comp stuff
##------------------------------
zmodload zsh/complist 
autoload -Uz compinit
compinit


#------------------------------
# Alias stuff
#------------------------------
alias cp='cp -r'
alias ls='ls -F'
alias l='ls -Flha'


#-----------------
# Options
#-----------------

setopt AUTO_CD               # implicate cd for non-commands
#setopt CD_ABLE_VARS       # read vars in cd
setopt CORRECT_ALL            # correct spelling
setopt COMPLETE_IN_WORD    # complete commands anywhere in the word
setopt NOTIFY              # Notify when jobs finish
setopt BASH_AUTO_LIST      # Autolist options on repeition of ambiguous args
setopt AUTO_PUSHD          # Push dirs into history
#setopt ALWAYS_TO_END       # Move to the end on complete completion
#setopt LIST_ROWS_FIRST     # Row orientation for menu
setopt MULTIOS             # Allow Multiple pipes
setopt MAGIC_EQUAL_SUBST   # Expand inside equals
setopt EXTENDED_GLOB
setopt NOBEEP
setopt INC_APPEND_HISTORY
export HISTSIZE=1000
export SAVEHIST=1000
export HISTFILE=~/.zhistory
setopt hist_ignore_all_dups
setopt hist_ignore_space
